using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class CityManager : MonoBehaviour {

	private List<Tuple<string, string>> connections = new List<Tuple<string, string>>
	{
		Tuple.Create("Chicago", "SanFrancisco"),
		Tuple.Create("Chicago", "LosAngeles"),
		Tuple.Create("Chicago", "MexicoCity"),
		Tuple.Create("Chicago", "Atlanta"),
		Tuple.Create("Chicago", "Montreal"),
		Tuple.Create("Montreal", "Chicago"),
		Tuple.Create("Montreal", "NewYork"),
		Tuple.Create("Montreal", "Washington"),
		Tuple.Create("Washington", "Montreal"),
		Tuple.Create("Washington", "Atlanta"),
		Tuple.Create("Washington", "Miami"),
        Tuple.Create("Washington", "NewYork"),
        Tuple.Create("Atlanta", "Chicago"), 
		Tuple.Create("Atlanta", "Washington"),
		Tuple.Create("Atlanta", "Miami"),
		Tuple.Create("Miami", "Atlanta"),
		Tuple.Create("Miami", "MexicoCity"),
		Tuple.Create("Miami", "Bogota"),
		Tuple.Create("Bogota", "Miami"),
		Tuple.Create("Bogota", "MexicoCity"),
		Tuple.Create("Bogota", "Lima"),
		Tuple.Create("Bogota", "SaoPaulo"),
		Tuple.Create("Bogota", "BuenosAries"),
		Tuple.Create("BuenosAries","Bogota"),
		Tuple.Create("BuenosAries","SaoPaulo"),
		Tuple.Create("SaoPaulo", "BuenosAries"),
		Tuple.Create("SaoPaulo", "Bogota"),
		Tuple.Create("SaoPaulo", "Madrid"),
		Tuple.Create("SaoPaulo", "Lagos"),
		Tuple.Create("Lagos", "SaoPaulo"),
		Tuple.Create("Lagos", "Khartoum"),
		Tuple.Create("Lagos", "Kinshasa"),
		Tuple.Create("Kinshasa", "Lagos"),
		Tuple.Create("Kinshasa", "Khartoum"),
		Tuple.Create("Kinshasa", "Johannesburg"),
		Tuple.Create("Johannesburg", "Kinshasa"),
		Tuple.Create("Johannesburg", "Khartoum"),
		Tuple.Create("Khartoum", "Johannesburg"),
		Tuple.Create("Khartoum", "Lagos"),
		Tuple.Create("Khartoum", "Cairo"),
		Tuple.Create("Cairo", "Khartoum"),
		Tuple.Create("Cairo", "Riyadh"),
		Tuple.Create("Cairo", "Baghdad"),
		Tuple.Create("Cairo", "Istanbul"),
		Tuple.Create("Cairo", "Algiers"),
		Tuple.Create("Algiers", "Cairo"),
		Tuple.Create("Algiers", "Istanbul"),
		Tuple.Create("Algiers", "Paris"),
		Tuple.Create("Algiers", "Madrid"),
		Tuple.Create("Madrid", "Algiers"),
		Tuple.Create("Madrid", "Paris"),
		Tuple.Create("Madrid", "London"),
		Tuple.Create("Madrid", "NewYork"),
		Tuple.Create("NewYork", "Madrid"),
		Tuple.Create("NewYork", "Montreal"),
		Tuple.Create("NewYork", "Washington"),
		Tuple.Create("NewYork", "London"),
		Tuple.Create("London", "NewYork"),
		Tuple.Create("London", "Madrid"),
		Tuple.Create("London", "Essen"),
		Tuple.Create("London", "Paris"),
		Tuple.Create("Paris", "London"),
		Tuple.Create("Paris", "Madrid"),
		Tuple.Create("Paris", "Algiers"),
		Tuple.Create("Paris", "Milan"),
		Tuple.Create("Paris", "Essen"),
		Tuple.Create("Essen", "Paris"),
		Tuple.Create("Essen", "London"),
		Tuple.Create("Essen", "Milan"),
		Tuple.Create("Milan", "Essen"),
		Tuple.Create("Milan", "Paris"),
		Tuple.Create("Milan", "Istanbul"),
		Tuple.Create("Istanbul", "Algiers"),
		Tuple.Create("Istanbul", "Cairo"),
		Tuple.Create("Istanbul", "Baghdad"),
		Tuple.Create("Istanbul", "Moscow"),
		Tuple.Create("Istanbul", "StPetersburg"),
		Tuple.Create("StPetersburg", "Istanbul"),
		Tuple.Create("StPetersburg", "Essen"),
		Tuple.Create("StPetersburg", "Moscow"),
		Tuple.Create("Moscow", "StPetersburg"),
		Tuple.Create("Moscow", "Istanbul"),
		Tuple.Create("Moscow", "Tehran"),
		Tuple.Create("Tehran", "Moscow"),
		Tuple.Create("Tehran", "Delhi"),
		Tuple.Create("Tehran", "Karachi"),
		Tuple.Create("Tehran", "Baghdad"),
		Tuple.Create("Baghdad", "Tehran"),
		Tuple.Create("Baghdad", "Karachi"),
		Tuple.Create("Baghdad", "Riyadh"),
		Tuple.Create("Baghdad", "Cairo"),
		Tuple.Create("Baghdad", "Istanbul"),
		Tuple.Create("Riyadh", "Cairo"),
		Tuple.Create("Riyadh", "Baghdad"),
		Tuple.Create("Riyadh", "Karachi"),
		Tuple.Create("Karachi", "Riyadh"),
		Tuple.Create("Karachi", "Baghdad"),
		Tuple.Create("Karachi", "Tehran"),
		Tuple.Create("Karachi", "Delhi"),
		Tuple.Create("Karachi", "Mumbai"),
		Tuple.Create("Mumbai", "Karachi"),
		Tuple.Create("Mumbai", "Delhi"),
		Tuple.Create("Mumbai", "Chennai"),
		Tuple.Create("Chennai", "Mumbai"),
		Tuple.Create("Chennai", "Kolkata"),
		Tuple.Create("Chennai", "Jakarta"),
		Tuple.Create("Chennai", "Delhi"),
		Tuple.Create("Delhi", "Chennai"),
		Tuple.Create("Delhi", "Mumbai"),
		Tuple.Create("Delhi", "Karachi"),
		Tuple.Create("Delhi", "Tehran"),
		Tuple.Create("Delhi", "Kolkata"),
		Tuple.Create("Kolkata", "Delhi"),
		Tuple.Create("Kolkata", "Chennai"),
		Tuple.Create("Kolkata", "HongKong"),
		Tuple.Create("Kolkata", "Bangkok"),
		Tuple.Create("Bangkok", "Kolkata"),
		Tuple.Create("Bangkok", "Chennai"),
		Tuple.Create("Bangkok", "HongKong"),
		Tuple.Create("Bangkok", "HoChiMinhCity"),
		Tuple.Create("Bangkok", "Jakarta"),
		Tuple.Create("Jakarta", "Bangkok"),
		Tuple.Create("Jakarta", "Chennai"),
		Tuple.Create("Jakarta", "Sydney"),
		Tuple.Create("Jakarta", "HoChiMinhCity"),
		Tuple.Create("HoChiMinhCity", "Jakarta"),
		Tuple.Create("HoChiMinhCity", "Bangkok"),
		Tuple.Create("HoChiMinhCity", "Manila"),
		Tuple.Create("HoChiMinhCity", "HongKong"),
		Tuple.Create("HongKong", "HoChiMinhCity"), 
		Tuple.Create("HongKong", "Kolkata"),
		Tuple.Create("HongKong", "Bangkok"),
		Tuple.Create("HongKong", "Manila"),
		Tuple.Create("HongKong", "Taipei"),
		Tuple.Create("HongKong", "Shanghai"),
		Tuple.Create("Shanghai", "HongKong"),
		Tuple.Create("Shanghai", "Taipei"),
		Tuple.Create("Shanghai", "Tokyo"),
		Tuple.Create("Shanghai", "Seoul"),
		Tuple.Create("Shanghai", "Beijing"),
		Tuple.Create("Beijing", "Shanghai"),
		Tuple.Create("Beijing", "Seoul"),
		Tuple.Create("Seoul", "Beijing"),
		Tuple.Create("Seoul", "Shanghai"),
		Tuple.Create("Seoul", "Tokyo"),
		Tuple.Create("Tokyo", "Seoul"),
		Tuple.Create("Tokyo", "Shanghai"),
		Tuple.Create("Tokyo", "SanFrancisco"),
		Tuple.Create("Tokyo", "Osaka"),
		Tuple.Create("Osaka", "Tokyo"),
		Tuple.Create("Osaka", "Taipei"),
		Tuple.Create("Taipei", "Osaka"),
		Tuple.Create("Taipei", "Shanghai"),
		Tuple.Create("Taipei", "HongKong"),
		Tuple.Create("Taipei", "Manila"),
		Tuple.Create("Manila", "Taipei"),
		Tuple.Create("Manila", "SanFrancisco"),
		Tuple.Create("Manila", "HongKong"), 
		Tuple.Create("Manila", "HoChiMinhCity"),
		Tuple.Create("Manila", "Sydnei"),
		Tuple.Create("Sydney", "Manila"),
		Tuple.Create("Sydney", "Jakarta"),
		Tuple.Create("Sydney", "LosAngeles"), 
		Tuple.Create("LosAngeles", "Sydney"),
		Tuple.Create("LosAngeles", "MexicoCity"),
		Tuple.Create("LosAngeles", "SanFrancisco"),
		Tuple.Create("SanFrancisco", "LosAngeles"),
		Tuple.Create("SanFrancisco", "Manila"),
		Tuple.Create("SanFrancisco", "Tokyo"),
		Tuple.Create("SanFrancisco", "Chicago"),
		Tuple.Create("MexicoCity", "Chicago"),
		Tuple.Create("MexicoCity", "LosAngeles"),
		Tuple.Create("MexicoCity", "Miami"),
		Tuple.Create("MexicoCity", "Bogota"),
		Tuple.Create("MexicoCity", "Lima"),
        Tuple.Create("Lima","Bogota"),
        Tuple.Create("Lima", "MexicoCity"),
		Tuple.Create("Lima", "Santiago"),
		Tuple.Create("Santiago", "Lima")
	};

	public List<GameObject> GetNeighbors(GameObject city){
		List<GameObject> neighbors = new List<GameObject>();
		string cityName = city.name;
		
		foreach (Tuple<string, string> connection in connections){
			if(connection.Item1.Equals(cityName)){
				neighbors.Add(GameObject.Find(connection.Item2));
			}
		}
		return neighbors;
	}

    public bool AreNeighbors(GameObject city1, GameObject city2)
    {
        List<GameObject> neighbors = GetNeighbors(city1);

        foreach (GameObject city in neighbors)
        {
            if (city2.Equals(city))
            {
                return true;
            }
        }
        return false;
    }

}
